// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function $at$bang(g, f, x) {
  return Curry._1(g, Curry._1(f, x));
}

exports.$at$bang = $at$bang;
/* No side effect */
